version: '3.2'
services:
  devdb:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=asdf1234
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080