version: '3.2'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=NotSoSecretP455W0RD
  webapp:
    build: ./app
    ports:
      - 8080:8080
  api:
    build: ./services/api
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=NotSoSecretP455W0RD
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080