version: '3.2'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=NotSoSecretP455W0RD
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_PORT=5433
      - DB_PASSWORD=NotSoSecretP455W0RD
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080