// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

package basicblog_post

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewCommand struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewCommand) Reset()         { *m = NewCommand{} }
func (m *NewCommand) String() string { return proto.CompactTextString(m) }
func (*NewCommand) ProtoMessage()    {}
func (*NewCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{0}
}

func (m *NewCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCommand.Unmarshal(m, b)
}
func (m *NewCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCommand.Marshal(b, m, deterministic)
}
func (m *NewCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCommand.Merge(m, src)
}
func (m *NewCommand) XXX_Size() int {
	return xxx_messageInfo_NewCommand.Size(m)
}
func (m *NewCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCommand.DiscardUnknown(m)
}

var xxx_messageInfo_NewCommand proto.InternalMessageInfo

func (m *NewCommand) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NewCommand) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type NewResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewResponse) Reset()         { *m = NewResponse{} }
func (m *NewResponse) String() string { return proto.CompactTextString(m) }
func (*NewResponse) ProtoMessage()    {}
func (*NewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{1}
}

func (m *NewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewResponse.Unmarshal(m, b)
}
func (m *NewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewResponse.Marshal(b, m, deterministic)
}
func (m *NewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewResponse.Merge(m, src)
}
func (m *NewResponse) XXX_Size() int {
	return xxx_messageInfo_NewResponse.Size(m)
}
func (m *NewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewResponse proto.InternalMessageInfo

func (m *NewResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCommand struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCommand) Reset()         { *m = DeleteCommand{} }
func (m *DeleteCommand) String() string { return proto.CompactTextString(m) }
func (*DeleteCommand) ProtoMessage()    {}
func (*DeleteCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{2}
}

func (m *DeleteCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCommand.Unmarshal(m, b)
}
func (m *DeleteCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCommand.Marshal(b, m, deterministic)
}
func (m *DeleteCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCommand.Merge(m, src)
}
func (m *DeleteCommand) XXX_Size() int {
	return xxx_messageInfo_DeleteCommand.Size(m)
}
func (m *DeleteCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCommand.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCommand proto.InternalMessageInfo

func (m *DeleteCommand) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RestoreCommand struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreCommand) Reset()         { *m = RestoreCommand{} }
func (m *RestoreCommand) String() string { return proto.CompactTextString(m) }
func (*RestoreCommand) ProtoMessage()    {}
func (*RestoreCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{4}
}

func (m *RestoreCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreCommand.Unmarshal(m, b)
}
func (m *RestoreCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreCommand.Marshal(b, m, deterministic)
}
func (m *RestoreCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreCommand.Merge(m, src)
}
func (m *RestoreCommand) XXX_Size() int {
	return xxx_messageInfo_RestoreCommand.Size(m)
}
func (m *RestoreCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreCommand proto.InternalMessageInfo

func (m *RestoreCommand) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RestoreResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreResponse) Reset()         { *m = RestoreResponse{} }
func (m *RestoreResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreResponse) ProtoMessage()    {}
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{5}
}

func (m *RestoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreResponse.Unmarshal(m, b)
}
func (m *RestoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreResponse.Marshal(b, m, deterministic)
}
func (m *RestoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreResponse.Merge(m, src)
}
func (m *RestoreResponse) XXX_Size() int {
	return xxx_messageInfo_RestoreResponse.Size(m)
}
func (m *RestoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreResponse proto.InternalMessageInfo

func (m *RestoreResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type EditCommand struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditCommand) Reset()         { *m = EditCommand{} }
func (m *EditCommand) String() string { return proto.CompactTextString(m) }
func (*EditCommand) ProtoMessage()    {}
func (*EditCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{6}
}

func (m *EditCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditCommand.Unmarshal(m, b)
}
func (m *EditCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditCommand.Marshal(b, m, deterministic)
}
func (m *EditCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditCommand.Merge(m, src)
}
func (m *EditCommand) XXX_Size() int {
	return xxx_messageInfo_EditCommand.Size(m)
}
func (m *EditCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_EditCommand.DiscardUnknown(m)
}

var xxx_messageInfo_EditCommand proto.InternalMessageInfo

func (m *EditCommand) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditCommand) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EditCommand) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type EditResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditResponse) Reset()         { *m = EditResponse{} }
func (m *EditResponse) String() string { return proto.CompactTextString(m) }
func (*EditResponse) ProtoMessage()    {}
func (*EditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{7}
}

func (m *EditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditResponse.Unmarshal(m, b)
}
func (m *EditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditResponse.Marshal(b, m, deterministic)
}
func (m *EditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditResponse.Merge(m, src)
}
func (m *EditResponse) XXX_Size() int {
	return xxx_messageInfo_EditResponse.Size(m)
}
func (m *EditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditResponse proto.InternalMessageInfo

func (m *EditResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListQuery struct {
	IncludeDeleted       bool     `protobuf:"varint,1,opt,name=includeDeleted,proto3" json:"includeDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQuery) Reset()         { *m = ListQuery{} }
func (m *ListQuery) String() string { return proto.CompactTextString(m) }
func (*ListQuery) ProtoMessage()    {}
func (*ListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{8}
}

func (m *ListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuery.Unmarshal(m, b)
}
func (m *ListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuery.Marshal(b, m, deterministic)
}
func (m *ListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuery.Merge(m, src)
}
func (m *ListQuery) XXX_Size() int {
	return xxx_messageInfo_ListQuery.Size(m)
}
func (m *ListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuery proto.InternalMessageInfo

func (m *ListQuery) GetIncludeDeleted() bool {
	if m != nil {
		return m.IncludeDeleted
	}
	return false
}

type ListResponse struct {
	Posts                []*ViewResponse `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{9}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetPosts() []*ViewResponse {
	if m != nil {
		return m.Posts
	}
	return nil
}

type ViewQuery struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IncludeDeleted       bool     `protobuf:"varint,2,opt,name=includeDeleted,proto3" json:"includeDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewQuery) Reset()         { *m = ViewQuery{} }
func (m *ViewQuery) String() string { return proto.CompactTextString(m) }
func (*ViewQuery) ProtoMessage()    {}
func (*ViewQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{10}
}

func (m *ViewQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewQuery.Unmarshal(m, b)
}
func (m *ViewQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewQuery.Marshal(b, m, deterministic)
}
func (m *ViewQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewQuery.Merge(m, src)
}
func (m *ViewQuery) XXX_Size() int {
	return xxx_messageInfo_ViewQuery.Size(m)
}
func (m *ViewQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ViewQuery proto.InternalMessageInfo

func (m *ViewQuery) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ViewQuery) GetIncludeDeleted() bool {
	if m != nil {
		return m.IncludeDeleted
	}
	return false
}

type ViewResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	CreatedTime          int64    `protobuf:"varint,5,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	Deleted              bool     `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewResponse) Reset()         { *m = ViewResponse{} }
func (m *ViewResponse) String() string { return proto.CompactTextString(m) }
func (*ViewResponse) ProtoMessage()    {}
func (*ViewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{11}
}

func (m *ViewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewResponse.Unmarshal(m, b)
}
func (m *ViewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewResponse.Marshal(b, m, deterministic)
}
func (m *ViewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewResponse.Merge(m, src)
}
func (m *ViewResponse) XXX_Size() int {
	return xxx_messageInfo_ViewResponse.Size(m)
}
func (m *ViewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ViewResponse proto.InternalMessageInfo

func (m *ViewResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ViewResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ViewResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ViewResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *ViewResponse) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *ViewResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func init() {
	proto.RegisterType((*NewCommand)(nil), "basicblog.post.NewCommand")
	proto.RegisterType((*NewResponse)(nil), "basicblog.post.NewResponse")
	proto.RegisterType((*DeleteCommand)(nil), "basicblog.post.DeleteCommand")
	proto.RegisterType((*DeleteResponse)(nil), "basicblog.post.DeleteResponse")
	proto.RegisterType((*RestoreCommand)(nil), "basicblog.post.RestoreCommand")
	proto.RegisterType((*RestoreResponse)(nil), "basicblog.post.RestoreResponse")
	proto.RegisterType((*EditCommand)(nil), "basicblog.post.EditCommand")
	proto.RegisterType((*EditResponse)(nil), "basicblog.post.EditResponse")
	proto.RegisterType((*ListQuery)(nil), "basicblog.post.ListQuery")
	proto.RegisterType((*ListResponse)(nil), "basicblog.post.ListResponse")
	proto.RegisterType((*ViewQuery)(nil), "basicblog.post.ViewQuery")
	proto.RegisterType((*ViewResponse)(nil), "basicblog.post.ViewResponse")
}

func init() { proto.RegisterFile("post.proto", fileDescriptor_e114ad14deab1dd1) }

var fileDescriptor_e114ad14deab1dd1 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x86, 0xb7, 0x49, 0xda, 0xb5, 0xa7, 0x35, 0xc2, 0x20, 0x12, 0xe3, 0xae, 0x5b, 0xe6, 0x42,
	0x82, 0x42, 0x2e, 0xba, 0xe0, 0xb5, 0x5a, 0x45, 0x84, 0xa5, 0x68, 0x10, 0xef, 0x93, 0xcc, 0x41,
	0x07, 0xd2, 0x4e, 0xc9, 0x4c, 0x28, 0xfb, 0x2e, 0x3e, 0x82, 0x0f, 0x29, 0x93, 0x49, 0xd3, 0x69,
	0x92, 0xca, 0xe2, 0x5d, 0xcf, 0x39, 0x7f, 0xbe, 0x39, 0xf3, 0xcf, 0x4f, 0x01, 0x76, 0x42, 0xaa,
	0x78, 0x57, 0x0a, 0x25, 0x88, 0x9f, 0xa5, 0x92, 0xe7, 0x59, 0x21, 0x7e, 0xc6, 0xba, 0x4b, 0xdf,
	0x02, 0xac, 0x71, 0xbf, 0x12, 0x9b, 0x4d, 0xba, 0x65, 0xe4, 0x29, 0x8c, 0x15, 0x57, 0x05, 0x06,
	0xa3, 0xc5, 0x28, 0x9a, 0x26, 0xa6, 0x20, 0x04, 0xbc, 0x4c, 0xb0, 0xfb, 0xc0, 0xa9, 0x9b, 0xf5,
	0x6f, 0x7a, 0x0d, 0xb3, 0x35, 0xee, 0x13, 0x94, 0x3b, 0xb1, 0x95, 0x48, 0x7c, 0x70, 0x38, 0xab,
	0xbf, 0x1a, 0x27, 0x0e, 0x67, 0xf4, 0x06, 0x1e, 0x7f, 0xc4, 0x02, 0x15, 0x1e, 0xc8, 0x5d, 0xc1,
	0x6b, 0xf0, 0x8d, 0xa0, 0x45, 0x04, 0x70, 0x29, 0xab, 0x3c, 0x47, 0x29, 0x6b, 0xd9, 0xa3, 0xe4,
	0x50, 0xd2, 0x05, 0xf8, 0x09, 0x4a, 0x25, 0xca, 0xb3, 0xb4, 0x37, 0xf0, 0xa4, 0x51, 0x3c, 0x00,
	0xf7, 0x19, 0x66, 0x9f, 0x18, 0x57, 0x67, 0x58, 0x47, 0x0f, 0x9c, 0x21, 0x0f, 0x5c, 0xcb, 0x83,
	0x08, 0xe6, 0x1a, 0xf4, 0x80, 0x23, 0x6f, 0x61, 0x7a, 0xc7, 0xa5, 0xfa, 0x56, 0x61, 0x79, 0x4f,
	0x5e, 0x81, 0xcf, 0xb7, 0x79, 0x51, 0x31, 0x34, 0x0e, 0xb0, 0x46, 0xdd, 0xe9, 0xd2, 0x0f, 0x30,
	0xd7, 0x1f, 0xb5, 0xf8, 0x25, 0x8c, 0xf5, 0x93, 0x69, 0xb8, 0x1b, 0xcd, 0x96, 0x57, 0xf1, 0xe9,
	0x53, 0xc6, 0x3f, 0xf8, 0xf1, 0x41, 0x12, 0x23, 0xa5, 0x2b, 0x98, 0xea, 0xb6, 0x39, 0xb8, 0x7b,
	0xd3, 0xfe, 0x22, 0xce, 0xe0, 0x22, 0xbf, 0x47, 0x30, 0xb7, 0xe1, 0xff, 0x6f, 0x19, 0x79, 0x06,
	0x93, 0xb4, 0x52, 0xbf, 0x44, 0x19, 0x78, 0x75, 0xb7, 0xa9, 0xc8, 0x02, 0x66, 0x79, 0x89, 0xa9,
	0x42, 0xf6, 0x9d, 0x6f, 0x30, 0x18, 0x2f, 0x46, 0x91, 0x9b, 0xd8, 0x2d, 0x6d, 0x2e, 0x6b, 0xb6,
	0x9c, 0x18, 0x73, 0x9b, 0x72, 0xf9, 0xc7, 0x05, 0xef, 0xab, 0x90, 0x8a, 0xbc, 0x03, 0x77, 0x8d,
	0x7b, 0x12, 0x76, 0x8d, 0x39, 0x06, 0x3c, 0x7c, 0x31, 0x30, 0x3b, 0x5c, 0x8b, 0x5e, 0x90, 0x2f,
	0x30, 0x31, 0x97, 0x26, 0xd7, 0x5d, 0xe1, 0x49, 0x9c, 0xc3, 0x97, 0xc3, 0x63, 0x0b, 0x75, 0x07,
	0x97, 0x4d, 0x24, 0x49, 0x4f, 0x7c, 0x9a, 0xe6, 0xf0, 0xe6, 0xcc, 0xdc, 0xa2, 0xad, 0xc0, 0xd3,
	0x51, 0x23, 0xbd, 0xfd, 0xad, 0x24, 0x87, 0x57, 0x43, 0x43, 0x0b, 0xf2, 0x1e, 0x3c, 0x1d, 0x28,
	0xf2, 0xbc, 0xab, 0x6b, 0xb3, 0xd9, 0x47, 0xd8, 0x09, 0x34, 0x08, 0x9d, 0x84, 0x3e, 0xa2, 0x4d,
	0x59, 0xf8, 0xcf, 0x5c, 0xd2, 0x8b, 0x6c, 0x52, 0xff, 0x11, 0xdd, 0xfe, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0xe1, 0x5f, 0x3e, 0xf1, 0x96, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostClient is the client API for Post service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostClient interface {
	New(ctx context.Context, in *NewCommand, opts ...grpc.CallOption) (*NewResponse, error)
	Delete(ctx context.Context, in *DeleteCommand, opts ...grpc.CallOption) (*DeleteResponse, error)
	Restore(ctx context.Context, in *RestoreCommand, opts ...grpc.CallOption) (*RestoreResponse, error)
	Edit(ctx context.Context, in *EditCommand, opts ...grpc.CallOption) (*EditResponse, error)
	List(ctx context.Context, in *ListQuery, opts ...grpc.CallOption) (*ListResponse, error)
	View(ctx context.Context, in *ViewQuery, opts ...grpc.CallOption) (*ViewResponse, error)
}

type postClient struct {
	cc *grpc.ClientConn
}

func NewPostClient(cc *grpc.ClientConn) PostClient {
	return &postClient{cc}
}

func (c *postClient) New(ctx context.Context, in *NewCommand, opts ...grpc.CallOption) (*NewResponse, error) {
	out := new(NewResponse)
	err := c.cc.Invoke(ctx, "/basicblog.post.Post/New", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) Delete(ctx context.Context, in *DeleteCommand, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/basicblog.post.Post/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) Restore(ctx context.Context, in *RestoreCommand, opts ...grpc.CallOption) (*RestoreResponse, error) {
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, "/basicblog.post.Post/Restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) Edit(ctx context.Context, in *EditCommand, opts ...grpc.CallOption) (*EditResponse, error) {
	out := new(EditResponse)
	err := c.cc.Invoke(ctx, "/basicblog.post.Post/Edit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) List(ctx context.Context, in *ListQuery, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/basicblog.post.Post/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) View(ctx context.Context, in *ViewQuery, opts ...grpc.CallOption) (*ViewResponse, error) {
	out := new(ViewResponse)
	err := c.cc.Invoke(ctx, "/basicblog.post.Post/View", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServer is the server API for Post service.
type PostServer interface {
	New(context.Context, *NewCommand) (*NewResponse, error)
	Delete(context.Context, *DeleteCommand) (*DeleteResponse, error)
	Restore(context.Context, *RestoreCommand) (*RestoreResponse, error)
	Edit(context.Context, *EditCommand) (*EditResponse, error)
	List(context.Context, *ListQuery) (*ListResponse, error)
	View(context.Context, *ViewQuery) (*ViewResponse, error)
}

// UnimplementedPostServer can be embedded to have forward compatible implementations.
type UnimplementedPostServer struct {
}

func (*UnimplementedPostServer) New(ctx context.Context, req *NewCommand) (*NewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method New not implemented")
}
func (*UnimplementedPostServer) Delete(ctx context.Context, req *DeleteCommand) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedPostServer) Restore(ctx context.Context, req *RestoreCommand) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (*UnimplementedPostServer) Edit(ctx context.Context, req *EditCommand) (*EditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Edit not implemented")
}
func (*UnimplementedPostServer) List(ctx context.Context, req *ListQuery) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedPostServer) View(ctx context.Context, req *ViewQuery) (*ViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}

func RegisterPostServer(s *grpc.Server, srv PostServer) {
	s.RegisterService(&_Post_serviceDesc, srv)
}

func _Post_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basicblog.post.Post/New",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).New(ctx, req.(*NewCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basicblog.post.Post/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).Delete(ctx, req.(*DeleteCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basicblog.post.Post/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).Restore(ctx, req.(*RestoreCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basicblog.post.Post/Edit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).Edit(ctx, req.(*EditCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basicblog.post.Post/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).List(ctx, req.(*ListQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basicblog.post.Post/View",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).View(ctx, req.(*ViewQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _Post_serviceDesc = grpc.ServiceDesc{
	ServiceName: "basicblog.post.Post",
	HandlerType: (*PostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "New",
			Handler:    _Post_New_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Post_Delete_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _Post_Restore_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _Post_Edit_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Post_List_Handler,
		},
		{
			MethodName: "View",
			Handler:    _Post_View_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
