// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comment.proto

package basicblog_comment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewCommand struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Commenter            string   `protobuf:"bytes,2,opt,name=commenter,proto3" json:"commenter,omitempty"`
	PostId               int32    `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewCommand) Reset()         { *m = NewCommand{} }
func (m *NewCommand) String() string { return proto.CompactTextString(m) }
func (*NewCommand) ProtoMessage()    {}
func (*NewCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{0}
}

func (m *NewCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCommand.Unmarshal(m, b)
}
func (m *NewCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCommand.Marshal(b, m, deterministic)
}
func (m *NewCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCommand.Merge(m, src)
}
func (m *NewCommand) XXX_Size() int {
	return xxx_messageInfo_NewCommand.Size(m)
}
func (m *NewCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCommand.DiscardUnknown(m)
}

var xxx_messageInfo_NewCommand proto.InternalMessageInfo

func (m *NewCommand) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *NewCommand) GetCommenter() string {
	if m != nil {
		return m.Commenter
	}
	return ""
}

func (m *NewCommand) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type NewResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewResponse) Reset()         { *m = NewResponse{} }
func (m *NewResponse) String() string { return proto.CompactTextString(m) }
func (*NewResponse) ProtoMessage()    {}
func (*NewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{1}
}

func (m *NewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewResponse.Unmarshal(m, b)
}
func (m *NewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewResponse.Marshal(b, m, deterministic)
}
func (m *NewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewResponse.Merge(m, src)
}
func (m *NewResponse) XXX_Size() int {
	return xxx_messageInfo_NewResponse.Size(m)
}
func (m *NewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewResponse proto.InternalMessageInfo

func (m *NewResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListQuery struct {
	PostId               int32    `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQuery) Reset()         { *m = ListQuery{} }
func (m *ListQuery) String() string { return proto.CompactTextString(m) }
func (*ListQuery) ProtoMessage()    {}
func (*ListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{2}
}

func (m *ListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuery.Unmarshal(m, b)
}
func (m *ListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuery.Marshal(b, m, deterministic)
}
func (m *ListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuery.Merge(m, src)
}
func (m *ListQuery) XXX_Size() int {
	return xxx_messageInfo_ListQuery.Size(m)
}
func (m *ListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuery proto.InternalMessageInfo

func (m *ListQuery) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type ListResponse struct {
	Comments             []*ViewResponse `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{3}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetComments() []*ViewResponse {
	if m != nil {
		return m.Comments
	}
	return nil
}

type ViewResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId               int32    `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Commenter            string   `protobuf:"bytes,4,opt,name=commenter,proto3" json:"commenter,omitempty"`
	CreatedTime          int64    `protobuf:"varint,5,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewResponse) Reset()         { *m = ViewResponse{} }
func (m *ViewResponse) String() string { return proto.CompactTextString(m) }
func (*ViewResponse) ProtoMessage()    {}
func (*ViewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{4}
}

func (m *ViewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewResponse.Unmarshal(m, b)
}
func (m *ViewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewResponse.Marshal(b, m, deterministic)
}
func (m *ViewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewResponse.Merge(m, src)
}
func (m *ViewResponse) XXX_Size() int {
	return xxx_messageInfo_ViewResponse.Size(m)
}
func (m *ViewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ViewResponse proto.InternalMessageInfo

func (m *ViewResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ViewResponse) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *ViewResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ViewResponse) GetCommenter() string {
	if m != nil {
		return m.Commenter
	}
	return ""
}

func (m *ViewResponse) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func init() {
	proto.RegisterType((*NewCommand)(nil), "basicblog.comment.NewCommand")
	proto.RegisterType((*NewResponse)(nil), "basicblog.comment.NewResponse")
	proto.RegisterType((*ListQuery)(nil), "basicblog.comment.ListQuery")
	proto.RegisterType((*ListResponse)(nil), "basicblog.comment.ListResponse")
	proto.RegisterType((*ViewResponse)(nil), "basicblog.comment.ViewResponse")
}

func init() { proto.RegisterFile("comment.proto", fileDescriptor_749aee09ea917828) }

var fileDescriptor_749aee09ea917828 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x4e, 0x83, 0x40,
	0x14, 0x74, 0xa1, 0xb4, 0xf2, 0xa8, 0x26, 0xee, 0x45, 0xd2, 0xb4, 0x96, 0x10, 0x0f, 0x9c, 0x38,
	0xd4, 0xa3, 0xc7, 0x26, 0x1a, 0xa3, 0x21, 0x71, 0x63, 0xf4, 0x68, 0x80, 0x7d, 0x31, 0x9b, 0x08,
	0x4b, 0x58, 0x0c, 0xe9, 0x37, 0xf8, 0x07, 0x7e, 0xad, 0x01, 0x11, 0xd6, 0x4a, 0x6f, 0xf0, 0x66,
	0x76, 0xde, 0xcc, 0xec, 0xc2, 0x49, 0x2a, 0xb3, 0x0c, 0xf3, 0x2a, 0x2c, 0x4a, 0x59, 0x49, 0x7a,
	0x96, 0xc4, 0x4a, 0xa4, 0xc9, 0xbb, 0x7c, 0x0b, 0x3b, 0xc0, 0x7f, 0x01, 0x88, 0xb0, 0xde, 0xca,
	0x2c, 0x8b, 0x73, 0x4e, 0x29, 0x4c, 0x12, 0xc9, 0x77, 0x2e, 0xf1, 0x48, 0x60, 0xb3, 0xf6, 0x9b,
	0x2e, 0xc1, 0xee, 0xc8, 0x58, 0xba, 0x46, 0x0b, 0x0c, 0x03, 0x7a, 0x0e, 0xb3, 0x42, 0xaa, 0xea,
	0x55, 0x70, 0xd7, 0xf4, 0x48, 0x60, 0xb1, 0x69, 0xf3, 0x7b, 0xc7, 0xfd, 0x15, 0x38, 0x11, 0xd6,
	0x0c, 0x55, 0x21, 0x73, 0x85, 0xf4, 0x14, 0x0c, 0xc1, 0x5b, 0x5d, 0x8b, 0x19, 0x82, 0xfb, 0x97,
	0x60, 0x3f, 0x08, 0x55, 0x3d, 0x7e, 0x60, 0xb9, 0xd3, 0x45, 0xc8, 0x1f, 0x91, 0x7b, 0x98, 0x37,
	0xac, 0x5e, 0xe5, 0x1a, 0x8e, 0xbb, 0xd5, 0xca, 0x25, 0x9e, 0x19, 0x38, 0x9b, 0x75, 0xf8, 0x2f,
	0x53, 0xf8, 0x2c, 0x86, 0xc5, 0xac, 0x3f, 0xe0, 0x7f, 0x12, 0x98, 0xeb, 0xd0, 0xbe, 0x27, 0xdd,
	0x86, 0xa1, 0xdb, 0xe8, 0x6b, 0x31, 0x0f, 0xd5, 0x32, 0xd9, 0xaf, 0xc5, 0x03, 0x27, 0x2d, 0x31,
	0xae, 0x90, 0x3f, 0x89, 0x0c, 0x5d, 0xcb, 0x23, 0x81, 0xc9, 0xf4, 0xd1, 0xe6, 0x8b, 0xc0, 0x6c,
	0xfb, 0xc3, 0xa7, 0x37, 0x60, 0x46, 0x58, 0xd3, 0xd5, 0x48, 0x96, 0xe1, 0x72, 0x16, 0x17, 0xe3,
	0xf0, 0x6f, 0x1c, 0xff, 0x88, 0xde, 0xc2, 0xa4, 0xa9, 0x8b, 0x2e, 0x47, 0x98, 0x7d, 0xdb, 0x8b,
	0xf5, 0x01, 0x74, 0x10, 0x4a, 0xa6, 0xed, 0x7b, 0xb9, 0xfa, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xb9,
	0xdc, 0x17, 0xa9, 0x40, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommentClient is the client API for Comment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommentClient interface {
	New(ctx context.Context, in *NewCommand, opts ...grpc.CallOption) (*NewResponse, error)
	List(ctx context.Context, in *ListQuery, opts ...grpc.CallOption) (*ListResponse, error)
}

type commentClient struct {
	cc *grpc.ClientConn
}

func NewCommentClient(cc *grpc.ClientConn) CommentClient {
	return &commentClient{cc}
}

func (c *commentClient) New(ctx context.Context, in *NewCommand, opts ...grpc.CallOption) (*NewResponse, error) {
	out := new(NewResponse)
	err := c.cc.Invoke(ctx, "/basicblog.comment.Comment/New", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) List(ctx context.Context, in *ListQuery, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/basicblog.comment.Comment/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServer is the server API for Comment service.
type CommentServer interface {
	New(context.Context, *NewCommand) (*NewResponse, error)
	List(context.Context, *ListQuery) (*ListResponse, error)
}

// UnimplementedCommentServer can be embedded to have forward compatible implementations.
type UnimplementedCommentServer struct {
}

func (*UnimplementedCommentServer) New(ctx context.Context, req *NewCommand) (*NewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method New not implemented")
}
func (*UnimplementedCommentServer) List(ctx context.Context, req *ListQuery) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterCommentServer(s *grpc.Server, srv CommentServer) {
	s.RegisterService(&_Comment_serviceDesc, srv)
}

func _Comment_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basicblog.comment.Comment/New",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).New(ctx, req.(*NewCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basicblog.comment.Comment/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).List(ctx, req.(*ListQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _Comment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "basicblog.comment.Comment",
	HandlerType: (*CommentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "New",
			Handler:    _Comment_New_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Comment_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comment.proto",
}
